language: python
python:
      - "3.6"

install:
  - pip install codecov
  - pip install coverage

script:
  - coverage run -m unittest tests/test_*.py

after_success:
  - codecov
  - python setup.py sdist
  - bash ./upload_to_nexus.sh
